// This file is auto-generated by @hey-api/openapi-ts

export const CategoryCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "CategoryCreate",
} as const;

export const CategoryResponseSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    is_deleted: {
      type: "boolean",
      title: "Is Deleted",
    },
  },
  type: "object",
  required: ["name", "id", "created_at", "updated_at", "is_deleted"],
  title: "CategoryResponse",
} as const;

export const CategoryUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
  },
  type: "object",
  title: "CategoryUpdate",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const ProductCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    price: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
      ],
      title: "Price",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    image_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2083,
          minLength: 1,
          format: "uri",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
    },
    category_id: {
      type: "integer",
      title: "Category Id",
    },
  },
  type: "object",
  required: ["name", "price", "description", "category_id"],
  title: "ProductCreate",
} as const;

export const ProductResponseSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    price: {
      type: "string",
      pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
      title: "Price",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    image_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2083,
          minLength: 1,
          format: "uri",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
    },
    category_id: {
      type: "integer",
      title: "Category Id",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    is_deleted: {
      type: "boolean",
      title: "Is Deleted",
    },
  },
  type: "object",
  required: [
    "name",
    "price",
    "description",
    "category_id",
    "id",
    "created_at",
    "updated_at",
    "is_deleted",
  ],
  title: "ProductResponse",
} as const;

export const ProductUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    price: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    is_active: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Is Active",
    },
    image_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2083,
          minLength: 1,
          format: "uri",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
    },
    category_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Category Id",
    },
  },
  type: "object",
  title: "ProductUpdate",
} as const;

export const UserCreateSchema = {
  properties: {
    fullname: {
      type: "string",
      title: "Fullname",
    },
    phone: {
      type: "string",
      maxLength: 8,
      minLength: 8,
      pattern: "^\\d{8}$",
      title: "Phone",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["fullname", "phone", "email", "password"],
  title: "UserCreate",
} as const;

export const UserResponseSchema = {
  properties: {
    fullname: {
      type: "string",
      title: "Fullname",
    },
    phone: {
      type: "string",
      maxLength: 8,
      minLength: 8,
      pattern: "^\\d{8}$",
      title: "Phone",
    },
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
    is_deleted: {
      type: "boolean",
      title: "Is Deleted",
    },
  },
  type: "object",
  required: [
    "fullname",
    "phone",
    "email",
    "id",
    "created_at",
    "updated_at",
    "is_deleted",
  ],
  title: "UserResponse",
} as const;

export const UserUpdateSchema = {
  properties: {
    fullname: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Fullname",
    },
    phone: {
      anyOf: [
        {
          type: "string",
          maxLength: 8,
          minLength: 8,
          pattern: "^\\d{8}$",
        },
        {
          type: "null",
        },
      ],
      title: "Phone",
    },
    email: {
      anyOf: [
        {
          type: "string",
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
  },
  type: "object",
  title: "UserUpdate",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
