// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://127.0.0.1:8000" | (string & {});
};

/**
 * Body_iniciar_session_users_login_post
 */
export type BodyIniciarSessionUsersLoginPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
  /**
   * Name
   */
  name: string;
};

/**
 * CategoryResponse
 */
export type CategoryResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Is Deleted
   */
  is_deleted: boolean;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
  /**
   * Name
   */
  name?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
  /**
   * Name
   */
  name: string;
  /**
   * Price
   */
  price: number | string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Category Id
   */
  category_id: number;
};

/**
 * ProductResponse
 */
export type ProductResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Price
   */
  price: string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Category Id
   */
  category_id: number;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Is Deleted
   */
  is_deleted: boolean;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Price
   */
  price?: number | string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Image Url
   */
  image_url?: string | null;
  /**
   * Category Id
   */
  category_id?: number | null;
};

/**
 * SignatureResponse
 */
export type SignatureResponse = {
  /**
   * Signature
   */
  signature: string;
  /**
   * Timestamp
   */
  timestamp: number;
  /**
   * Api Key
   */
  api_key: string;
  /**
   * Cloud Name
   */
  cloud_name: string;
  /**
   * Upload Preset
   */
  upload_preset: string;
  /**
   * Folder
   */
  folder: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Fullname
   */
  fullname: string;
  /**
   * Phone
   */
  phone: string;
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Fullname
   */
  fullname: string;
  /**
   * Phone
   */
  phone: string;
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Is Deleted
   */
  is_deleted: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Fullname
   */
  fullname?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Email
   */
  email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type RegisterUsersRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/users/register";
};

export type RegisterUsersRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUsersRegisterPostError =
  RegisterUsersRegisterPostErrors[keyof RegisterUsersRegisterPostErrors];

export type RegisterUsersRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse;
};

export type RegisterUsersRegisterPostResponse =
  RegisterUsersRegisterPostResponses[keyof RegisterUsersRegisterPostResponses];

export type IniciarSessionUsersLoginPostData = {
  body: BodyIniciarSessionUsersLoginPost;
  path?: never;
  query?: never;
  url: "/users/login";
};

export type IniciarSessionUsersLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type IniciarSessionUsersLoginPostError =
  IniciarSessionUsersLoginPostErrors[keyof IniciarSessionUsersLoginPostErrors];

export type IniciarSessionUsersLoginPostResponses = {
  /**
   * Response Iniciar Session Users Login Post
   *
   * Successful Response
   */
  201: {
    [key: string]: unknown;
  };
};

export type IniciarSessionUsersLoginPostResponse =
  IniciarSessionUsersLoginPostResponses[keyof IniciarSessionUsersLoginPostResponses];

export type CreateUsersCreatePostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/users/create";
};

export type CreateUsersCreatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUsersCreatePostError =
  CreateUsersCreatePostErrors[keyof CreateUsersCreatePostErrors];

export type CreateUsersCreatePostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse;
};

export type CreateUsersCreatePostResponse =
  CreateUsersCreatePostResponses[keyof CreateUsersCreatePostResponses];

export type ReadUsersReadEmailGetData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/users/read/{email}";
};

export type ReadUsersReadEmailGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUsersReadEmailGetError =
  ReadUsersReadEmailGetErrors[keyof ReadUsersReadEmailGetErrors];

export type ReadUsersReadEmailGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type ReadUsersReadEmailGetResponse =
  ReadUsersReadEmailGetResponses[keyof ReadUsersReadEmailGetResponses];

export type Read2UsersReadGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/read";
};

export type Read2UsersReadGetResponses = {
  /**
   * Response Read2 Users Read Get
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type Read2UsersReadGetResponse =
  Read2UsersReadGetResponses[keyof Read2UsersReadGetResponses];

export type Read3UsersReadDeletedEmailGetData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/users/read-deleted/{email}";
};

export type Read3UsersReadDeletedEmailGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type Read3UsersReadDeletedEmailGetError =
  Read3UsersReadDeletedEmailGetErrors[keyof Read3UsersReadDeletedEmailGetErrors];

export type Read3UsersReadDeletedEmailGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type Read3UsersReadDeletedEmailGetResponse =
  Read3UsersReadDeletedEmailGetResponses[keyof Read3UsersReadDeletedEmailGetResponses];

export type Read4UsersReadDeletedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/read-deleted";
};

export type Read4UsersReadDeletedGetResponses = {
  /**
   * Response Read4 Users Read Deleted Get
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type Read4UsersReadDeletedGetResponse =
  Read4UsersReadDeletedGetResponses[keyof Read4UsersReadDeletedGetResponses];

export type UpdateUsersUpdateEmailPutData = {
  body: UserUpdate;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/users/update/{email}";
};

export type UpdateUsersUpdateEmailPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUsersUpdateEmailPutError =
  UpdateUsersUpdateEmailPutErrors[keyof UpdateUsersUpdateEmailPutErrors];

export type UpdateUsersUpdateEmailPutResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type UpdateUsersUpdateEmailPutResponse =
  UpdateUsersUpdateEmailPutResponses[keyof UpdateUsersUpdateEmailPutResponses];

export type DeleteUsersDeleteEmailDeleteData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/users/delete/{email}";
};

export type DeleteUsersDeleteEmailDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUsersDeleteEmailDeleteError =
  DeleteUsersDeleteEmailDeleteErrors[keyof DeleteUsersDeleteEmailDeleteErrors];

export type DeleteUsersDeleteEmailDeleteResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type DeleteUsersDeleteEmailDeleteResponse =
  DeleteUsersDeleteEmailDeleteResponses[keyof DeleteUsersDeleteEmailDeleteResponses];

export type Delete2UsersDeleteDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/delete";
};

export type Delete2UsersDeleteDeleteResponses = {
  /**
   * Response Delete2 Users Delete Delete
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type Delete2UsersDeleteDeleteResponse =
  Delete2UsersDeleteDeleteResponses[keyof Delete2UsersDeleteDeleteResponses];

export type RestaurarUsersRestaurarEmailPatchData = {
  body?: never;
  path: {
    /**
     * Email
     */
    email: string;
  };
  query?: never;
  url: "/users/restaurar/{email}";
};

export type RestaurarUsersRestaurarEmailPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RestaurarUsersRestaurarEmailPatchError =
  RestaurarUsersRestaurarEmailPatchErrors[keyof RestaurarUsersRestaurarEmailPatchErrors];

export type RestaurarUsersRestaurarEmailPatchResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type RestaurarUsersRestaurarEmailPatchResponse =
  RestaurarUsersRestaurarEmailPatchResponses[keyof RestaurarUsersRestaurarEmailPatchResponses];

export type Restaurar2UsersRestaurarPatchData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/restaurar";
};

export type Restaurar2UsersRestaurarPatchResponses = {
  /**
   * Response Restaurar2 Users Restaurar Patch
   *
   * Successful Response
   */
  200: Array<UserResponse>;
};

export type Restaurar2UsersRestaurarPatchResponse =
  Restaurar2UsersRestaurarPatchResponses[keyof Restaurar2UsersRestaurarPatchResponses];

export type CreateCategoriesCreatePostData = {
  body: CategoryCreate;
  path?: never;
  query?: never;
  url: "/categories/create";
};

export type CreateCategoriesCreatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCategoriesCreatePostError =
  CreateCategoriesCreatePostErrors[keyof CreateCategoriesCreatePostErrors];

export type CreateCategoriesCreatePostResponses = {
  /**
   * Successful Response
   */
  201: CategoryResponse;
};

export type CreateCategoriesCreatePostResponse =
  CreateCategoriesCreatePostResponses[keyof CreateCategoriesCreatePostResponses];

export type ReadCategoriesReadNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/categories/read/{name}";
};

export type ReadCategoriesReadNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadCategoriesReadNameGetError =
  ReadCategoriesReadNameGetErrors[keyof ReadCategoriesReadNameGetErrors];

export type ReadCategoriesReadNameGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type ReadCategoriesReadNameGetResponse =
  ReadCategoriesReadNameGetResponses[keyof ReadCategoriesReadNameGetResponses];

export type Read2CategoriesReadGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/categories/read";
};

export type Read2CategoriesReadGetResponses = {
  /**
   * Response Read2 Categories Read Get
   *
   * Successful Response
   */
  200: Array<CategoryResponse>;
};

export type Read2CategoriesReadGetResponse =
  Read2CategoriesReadGetResponses[keyof Read2CategoriesReadGetResponses];

export type Read3CategoriesReadDeletedNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/categories/read-deleted/{name}";
};

export type Read3CategoriesReadDeletedNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type Read3CategoriesReadDeletedNameGetError =
  Read3CategoriesReadDeletedNameGetErrors[keyof Read3CategoriesReadDeletedNameGetErrors];

export type Read3CategoriesReadDeletedNameGetResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type Read3CategoriesReadDeletedNameGetResponse =
  Read3CategoriesReadDeletedNameGetResponses[keyof Read3CategoriesReadDeletedNameGetResponses];

export type Read4CategoriesReadDeletedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/categories/read-deleted";
};

export type Read4CategoriesReadDeletedGetResponses = {
  /**
   * Response Read4 Categories Read Deleted Get
   *
   * Successful Response
   */
  200: Array<CategoryResponse>;
};

export type Read4CategoriesReadDeletedGetResponse =
  Read4CategoriesReadDeletedGetResponses[keyof Read4CategoriesReadDeletedGetResponses];

export type UpdateCategoriesUpdateNamePutData = {
  body: CategoryUpdate;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/categories/update/{name}";
};

export type UpdateCategoriesUpdateNamePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCategoriesUpdateNamePutError =
  UpdateCategoriesUpdateNamePutErrors[keyof UpdateCategoriesUpdateNamePutErrors];

export type UpdateCategoriesUpdateNamePutResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type UpdateCategoriesUpdateNamePutResponse =
  UpdateCategoriesUpdateNamePutResponses[keyof UpdateCategoriesUpdateNamePutResponses];

export type DeleteCategoriesDeleteNameDeleteData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/categories/delete/{name}";
};

export type DeleteCategoriesDeleteNameDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCategoriesDeleteNameDeleteError =
  DeleteCategoriesDeleteNameDeleteErrors[keyof DeleteCategoriesDeleteNameDeleteErrors];

export type DeleteCategoriesDeleteNameDeleteResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type DeleteCategoriesDeleteNameDeleteResponse =
  DeleteCategoriesDeleteNameDeleteResponses[keyof DeleteCategoriesDeleteNameDeleteResponses];

export type Delete2CategoriesDeleteDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/categories/delete";
};

export type Delete2CategoriesDeleteDeleteResponses = {
  /**
   * Response Delete2 Categories Delete Delete
   *
   * Successful Response
   */
  200: Array<CategoryResponse>;
};

export type Delete2CategoriesDeleteDeleteResponse =
  Delete2CategoriesDeleteDeleteResponses[keyof Delete2CategoriesDeleteDeleteResponses];

export type RestaurarCategoriesRestaurarNamePatchData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/categories/restaurar/{name}";
};

export type RestaurarCategoriesRestaurarNamePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RestaurarCategoriesRestaurarNamePatchError =
  RestaurarCategoriesRestaurarNamePatchErrors[keyof RestaurarCategoriesRestaurarNamePatchErrors];

export type RestaurarCategoriesRestaurarNamePatchResponses = {
  /**
   * Successful Response
   */
  200: CategoryResponse;
};

export type RestaurarCategoriesRestaurarNamePatchResponse =
  RestaurarCategoriesRestaurarNamePatchResponses[keyof RestaurarCategoriesRestaurarNamePatchResponses];

export type Restaurar2CategoriesRestaurarPatchData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/categories/restaurar";
};

export type Restaurar2CategoriesRestaurarPatchResponses = {
  /**
   * Response Restaurar2 Categories Restaurar Patch
   *
   * Successful Response
   */
  200: Array<CategoryResponse>;
};

export type Restaurar2CategoriesRestaurarPatchResponse =
  Restaurar2CategoriesRestaurarPatchResponses[keyof Restaurar2CategoriesRestaurarPatchResponses];

export type CreateProductsCreatePostData = {
  body: ProductCreate;
  path?: never;
  query?: never;
  url: "/products/create";
};

export type CreateProductsCreatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProductsCreatePostError =
  CreateProductsCreatePostErrors[keyof CreateProductsCreatePostErrors];

export type CreateProductsCreatePostResponses = {
  /**
   * Successful Response
   */
  201: ProductResponse;
};

export type CreateProductsCreatePostResponse =
  CreateProductsCreatePostResponses[keyof CreateProductsCreatePostResponses];

export type ReadProductsReadNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/products/read/{name}";
};

export type ReadProductsReadNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadProductsReadNameGetError =
  ReadProductsReadNameGetErrors[keyof ReadProductsReadNameGetErrors];

export type ReadProductsReadNameGetResponses = {
  /**
   * Successful Response
   */
  200: ProductResponse;
};

export type ReadProductsReadNameGetResponse =
  ReadProductsReadNameGetResponses[keyof ReadProductsReadNameGetResponses];

export type Read2ProductsReadGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products/read";
};

export type Read2ProductsReadGetResponses = {
  /**
   * Response Read2 Products Read Get
   *
   * Successful Response
   */
  200: Array<ProductResponse>;
};

export type Read2ProductsReadGetResponse =
  Read2ProductsReadGetResponses[keyof Read2ProductsReadGetResponses];

export type Read3ProductsReadDeletedNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/products/read-deleted/{name}";
};

export type Read3ProductsReadDeletedNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type Read3ProductsReadDeletedNameGetError =
  Read3ProductsReadDeletedNameGetErrors[keyof Read3ProductsReadDeletedNameGetErrors];

export type Read3ProductsReadDeletedNameGetResponses = {
  /**
   * Successful Response
   */
  200: ProductResponse;
};

export type Read3ProductsReadDeletedNameGetResponse =
  Read3ProductsReadDeletedNameGetResponses[keyof Read3ProductsReadDeletedNameGetResponses];

export type Read4ProductsReadDeletedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products/read-deleted";
};

export type Read4ProductsReadDeletedGetResponses = {
  /**
   * Response Read4 Products Read Deleted Get
   *
   * Successful Response
   */
  200: Array<ProductResponse>;
};

export type Read4ProductsReadDeletedGetResponse =
  Read4ProductsReadDeletedGetResponses[keyof Read4ProductsReadDeletedGetResponses];

export type UpdateProductsUpdateNamePutData = {
  body: ProductUpdate;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/products/update/{name}";
};

export type UpdateProductsUpdateNamePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProductsUpdateNamePutError =
  UpdateProductsUpdateNamePutErrors[keyof UpdateProductsUpdateNamePutErrors];

export type UpdateProductsUpdateNamePutResponses = {
  /**
   * Successful Response
   */
  200: ProductResponse;
};

export type UpdateProductsUpdateNamePutResponse =
  UpdateProductsUpdateNamePutResponses[keyof UpdateProductsUpdateNamePutResponses];

export type DeleteProductsDeleteNameDeleteData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/products/delete/{name}";
};

export type DeleteProductsDeleteNameDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProductsDeleteNameDeleteError =
  DeleteProductsDeleteNameDeleteErrors[keyof DeleteProductsDeleteNameDeleteErrors];

export type DeleteProductsDeleteNameDeleteResponses = {
  /**
   * Successful Response
   */
  200: ProductResponse;
};

export type DeleteProductsDeleteNameDeleteResponse =
  DeleteProductsDeleteNameDeleteResponses[keyof DeleteProductsDeleteNameDeleteResponses];

export type Delete2ProductsDeleteDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products/delete";
};

export type Delete2ProductsDeleteDeleteResponses = {
  /**
   * Response Delete2 Products Delete Delete
   *
   * Successful Response
   */
  200: Array<ProductResponse>;
};

export type Delete2ProductsDeleteDeleteResponse =
  Delete2ProductsDeleteDeleteResponses[keyof Delete2ProductsDeleteDeleteResponses];

export type RestaurarProductsRestaurarNamePatchData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/products/restaurar/{name}";
};

export type RestaurarProductsRestaurarNamePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RestaurarProductsRestaurarNamePatchError =
  RestaurarProductsRestaurarNamePatchErrors[keyof RestaurarProductsRestaurarNamePatchErrors];

export type RestaurarProductsRestaurarNamePatchResponses = {
  /**
   * Successful Response
   */
  200: ProductResponse;
};

export type RestaurarProductsRestaurarNamePatchResponse =
  RestaurarProductsRestaurarNamePatchResponses[keyof RestaurarProductsRestaurarNamePatchResponses];

export type Restaurar2ProductsRestaurarPatchData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/products/restaurar";
};

export type Restaurar2ProductsRestaurarPatchResponses = {
  /**
   * Response Restaurar2 Products Restaurar Patch
   *
   * Successful Response
   */
  200: Array<ProductResponse>;
};

export type Restaurar2ProductsRestaurarPatchResponse =
  Restaurar2ProductsRestaurarPatchResponses[keyof Restaurar2ProductsRestaurarPatchResponses];

export type CloudinarySignatureCloudinarySignaturePostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/cloudinary/signature";
};

export type CloudinarySignatureCloudinarySignaturePostResponses = {
  /**
   * Successful Response
   */
  201: SignatureResponse;
};

export type CloudinarySignatureCloudinarySignaturePostResponse =
  CloudinarySignatureCloudinarySignaturePostResponses[keyof CloudinarySignatureCloudinarySignaturePostResponses];

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Response Root  Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];
